# Docker Compose development overrides for BlackLab
# (configure JPDA to allow remote JVM debugging)

version: '3.9'

services:

  server:

    # Environment variables to pass to the container
    environment:
      # JPDA settings, to enable remote debugging
      - JPDA_ADDRESS=*:5005
      - JPDA_TRANSPORT=dt_socket

    # Start Tomcat with JPDA enabled
    command: catalina.sh jpda run

    # Map JPDA port
    ports:
      - "5005:5005"

